# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd5cafb514444124d601c5add14e16e40e7f90ab2cfe87cdfed119a0c5b4d4c35b1df0ea4ec98b6a53cfe52bbdaff8a3ce53b004cfc929b7612192f0b3350b21

test:
  secret_key_base: a6797591c44ff44a0863bcc31d5448c1ff5998b905d6824df90ef300fdcf11fc4ba4a01b48f88d682045fce95d9e90ed3feb4e78470d2fb7ce3e305ade29218c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
